//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APSEntities : DbContext
    {
        public APSEntities()
            : base("name=APSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APS_APPOINTMENT> APS_APPOINTMENT { get; set; }
        public virtual DbSet<APS_EMAIL_LOG> APS_EMAIL_LOG { get; set; }
        public virtual DbSet<APS_PWD_QUESTIONS> APS_PWD_QUESTIONS { get; set; }
        public virtual DbSet<APS_SMS_LOG> APS_SMS_LOG { get; set; }
        public virtual DbSet<APS_TIMESLOT> APS_TIMESLOT { get; set; }
        public virtual DbSet<APS_USER_INFO> APS_USER_INFO { get; set; }
        public virtual DbSet<APS_USERS> APS_USERS { get; set; }
        public virtual DbSet<APS_USER_ACT_LOG> APS_USER_ACT_LOG { get; set; }
        public virtual DbSet<V_APPOINTMENT_DETAILS> V_APPOINTMENT_DETAILS { get; set; }
        public virtual DbSet<V_TIMESLOT_DETAILS> V_TIMESLOT_DETAILS { get; set; }
    }
}
