//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_USERS
    {
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string IS_DELETED { get; set; }
        public int LOGIN_FAIL_ATTEMPT { get; set; }
        public int PWD_CHANGE_FAIL_ATTMPT { get; set; }
        public int DOB_FAIL_ATTEMPT { get; set; }
        public int PWD_QUES_ID { get; set; }
        public string PWD_QUES_ANSWER { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
