//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_USER_INFO
    {
        public long USER_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_FIRST_NAME { get; set; }
        public string USER_LAST_NAME { get; set; }
        public string USER_MOBILE_NO { get; set; }
        public string USER_EMAIL_ADDR { get; set; }
        public System.DateTime USER_DATE_OF_BIRTH { get; set; }
        public string CASE_OFFICER_NAME { get; set; }
        public string CASE_OFFICER_EMAIL { get; set; }
        public string CASE_OFFICER_MOBILE_NO { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_TIME { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_TIME { get; set; }
    }
}
