//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_APPOINTMENT_DETAILS
    {
        public long APP_ID { get; set; }
        public string APP_USERNAME { get; set; }
        public System.DateTime APP_DATE { get; set; }
        public int APP_TIMESLOT_ID { get; set; }
        public int APP_CHANGE_CNT { get; set; }
        public int APP_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_ON { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public System.DateTime LAST_UPDATED_ON { get; set; }
        public string TIMESLOT_CATEGORY { get; set; }
        public string TIMESLOT_DESC { get; set; }
        public string TIMESLOT_WEEKDAY { get; set; }
        public System.TimeSpan SLOT_START_TIME { get; set; }
        public System.TimeSpan SLOT_END_TIME { get; set; }
    }
}
